name: Central Policy Deployment (Multi-Tenant)

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches: [ main ] # Optional auto-trigger

permissions:
  contents: read       # Needed for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y jq
        az extension add --name managementgroups --yes || true

    - name: Deploy policies to all tenants
      env:
        APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
        APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
      run: |
        set -euxo pipefail

        TENANTS_FILE="${GITHUB_WORKSPACE}/tenants.json"

        if [ ! -f "$TENANTS_FILE" ]; then
          echo "tenants.json not found at $TENANTS_FILE"
          exit 1
        fi

        jq -c '.[]' "$TENANTS_FILE" | while read -r t; do
          tenantId=$(echo "$t" | jq -r '.tenantId')
          mgId=$(echo "$t" | jq -r '.rootMG')
          echo "----> Processing tenant: $tenantId (MG: $mgId)"

          # SPN login at MG level (no subscriptions needed)
          az account clear
          az login --service-principal \
            -u "$APP_CLIENT_ID" \
            -p "$APP_CLIENT_SECRET" \
            --tenant "$tenantId" \
            --allow-no-subscriptions

          # Optional: verify tenant login
          currentTenant=$(az account show --query tenantId -o tsv || echo "$tenantId")
          echo "Authenticated into tenant: $currentTenant"

          # Deploy policy definitions
          for file in policies/definitions/*.json; do
            [ -f "$file" ] || continue
            defName=$(basename "$file" .json)
            echo " -> Creating/updating policy definition $defName in MG $mgId"

            exists=$(az policy definition show --name "$defName" --management-group "$mgId" -o json 2>/dev/null || true)
            if [ -z "$exists" ]; then
              az policy definition create \
                --name "$defName" \
                --display-name "$defName" \
                --rules "$file" \
                --mode All \
                --management-group "$mgId"
            else
              az policy definition update \
                --name "$defName" \
                --rules "$file" \
                --management-group "$mgId"
            fi
          done

          echo "----> Finished tenant $tenantId"
        done
