name: Central Policy Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/setup-azure-cli@v2

      - name: Deploy policies to tenants
        run: |
          set -euxo pipefail

          TENANTS_FILE=tenants.json

          if [ ! -f "$TENANTS_FILE" ]; then
            echo "Missing tenants.json!"
            exit 1
          fi

          # Loop through each tenant
          jq -c '.[]' "$TENANTS_FILE" | while read -r t; do
            tenantId=$(echo "$t" | jq -r .tenantId)
            mgId=$(echo "$t" | jq -r .rootMG)
